pipeline:
  name: javascript-client
  identifier: javascriptclient
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: fmegithubharnessgitops
        repoName: javascript-client
        build: <+input>
  stages:
    - stage:
        name: Check-Test-Build-Upload
        identifier: Checkout_code
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: small
              imageSpec:
                imageName: ubuntu-latest
          buildIntelligence:
            enabled: false
          execution:
            steps:
              - step:
                  type: Action
                  name: Set up Node.js
                  identifier: Set_up_Nodejs
                  spec:
                    uses: dcodeIO/setup-node-nvm@master
                    with:
                      node-version: lts/*
              - step:
                  type: Run
                  name: Install Redis
                  identifier: Install_Redis
                  spec:
                    shell: Sh
                    command: |-
                      sudo add-apt-repository ppa:redislabs/redis
                      sudo apt-get install -y redis-tools redis-server
              - step:
                  type: Run
                  name: Check Redis
                  identifier: Check_Redis
                  spec:
                    shell: Sh
                    command: redis-cli ping
              - step:
                  type: Action
                  name: Setup Chrome
                  identifier: Setup_Chrome
                  spec:
                    uses: browser-actions/setup-chrome@19ae4b339ee18925ab85cf12c1041150ea4a44c8
                    with:
                      chrome-version: "125"
              - step:
                  type: Run
                  name: npm ci
                  identifier: npm_ci
                  spec:
                    shell: Sh
                    command: npm ci
                    envVariables:
                      PUPPETEER_SKIP_DOWNLOAD: "true"
              - step:
                  type: Run
                  name: npm ts tests
                  identifier: npm_ts_tests
                  spec:
                    shell: Sh
                    command: npm run test-ts-decls
              - step:
                  type: Run
                  name: npm run check
                  identifier: npm_run_check
                  spec:
                    shell: Sh
                    command: npm run check
              - step:
                  type: Run
                  name: npm test-browser
                  identifier: npm_test_browser
                  spec:
                    shell: Sh
                    command: |-
                      export CHROME_BIN=$(which chrome)
                      npm run test-browser
              - step:
                  type: Run
                  name: npm test-node
                  identifier: npm_test_node
                  spec:
                    shell: Sh
                    command: npm run test-node
              - step:
                  type: Run
                  name: npm run build
                  identifier: npm_run_build
                  spec:
                    shell: Sh
                    command: BUILD_BRANCH=<+codebase.branch> npm run build
              - parallel:
                  - step:
                      type: Run
                      name: upload dev assets to CDN
                      identifier: upload_dev_assets_to_CDN
                      spec:
                        shell: Sh
                        command: |-
                          aws s3 sync ./umd s3://split-public-stage/sdk --acl public-read --follow-symlinks --cache-control max-age=31536000,public
                        connectorRef: artifacts
                        envVariables:
                          AWS_DEFAULT_REGION: us-east-1
                      when:
                        stageStatus: Success
                        condition: <+trigger.event> == "PUSH" && <+trigger.branch> == "development"
                  - step:
                      type: Run
                      name: upload prod assets to CDN
                      identifier: upload_prod_assets_to_CDN
                      spec:
                        shell: Sh
                        command: |-
                          aws s3 sync ./umd s3://split-public/sdk --acl public-read --follow-symlinks --cache-control max-age=31536000,public
                        connectorRef: artifacts
                        envVariables:
                          AWS_DEFAULT_REGION: us-east-1
                      when:
                        stageStatus: Success
                        condition: <+trigger.event> == "PUSH" && <+trigger.branch> == "main"
