export const PushEventTypes = {
  PUSH_CONNECT: 'PUSH_CONNECT',
  PUSH_DISCONNECT: 'PUSH_DISCONNECT',
  SPLIT_UPDATE: 'SPLIT_UPDATE',
  SEGMENT_UPDATE: 'SEGMENT_UPDATE',
  MY_SEGMENTS_UPDATE: 'MY_SEGMENTS_UPDATE',
  SPLIT_KILL: 'SPLIT_KILL',
  // @TODO next constants might change
  STREAMING_DOWN: 'STREAMING_DOWN',
  STREAMING_UP: 'STREAMING_UP',
  RECONNECT: 'RECONNECT',
  error: 'error',
};

export const SECONDS_BEFORE_EXPIRATION = 600;