// flow-typed signature: 06ad2e6b35c0c2e289f9c835a05ef0e2
// flow-typed version: <<STUB>>/babel-preset-flow_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-flow/index' {
  declare module.exports: $Exports<'babel-preset-flow'>;
}
declare module 'babel-preset-flow/index.js' {
  declare module.exports: $Exports<'babel-preset-flow'>;
}
