// flow-typed signature: d570ee63dc15c00d9980c5ab4f988479
// flow-typed version: <<STUB>>/csv-streamify_v^3.0.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-streamify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-streamify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv-streamify/cli' {
  declare module.exports: any;
}

declare module 'csv-streamify/csv-streamify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv-streamify/cli.js' {
  declare module.exports: $Exports<'csv-streamify/cli'>;
}
declare module 'csv-streamify/csv-streamify.js' {
  declare module.exports: $Exports<'csv-streamify/csv-streamify'>;
}
