// flow-typed signature: 0b2d9737114d4c2b277a2ccf3c3f9400
// flow-typed version: <<STUB>>/karma-tap_v^3.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-tap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-tap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-tap/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-tap/lib/parser' {
  declare module.exports: any;
}

declare module 'karma-tap/src/adapter' {
  declare module.exports: any;
}

declare module 'karma-tap/src/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-tap/index' {
  declare module.exports: $Exports<'karma-tap'>;
}
declare module 'karma-tap/index.js' {
  declare module.exports: $Exports<'karma-tap'>;
}
declare module 'karma-tap/karma.conf.js' {
  declare module.exports: $Exports<'karma-tap/karma.conf'>;
}
declare module 'karma-tap/lib/parser.js' {
  declare module.exports: $Exports<'karma-tap/lib/parser'>;
}
declare module 'karma-tap/src/adapter.js' {
  declare module.exports: $Exports<'karma-tap/src/adapter'>;
}
declare module 'karma-tap/src/parser.js' {
  declare module.exports: $Exports<'karma-tap/src/parser'>;
}
