// flow-typed signature: 17559c79441aad28bfa0e6f9081a807b
// flow-typed version: <<STUB>>/karma-sauce-launcher_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-sauce-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-sauce-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-sauce-launcher/examples/karma.conf-ci' {
  declare module.exports: any;
}

declare module 'karma-sauce-launcher/examples/src/main' {
  declare module.exports: any;
}

declare module 'karma-sauce-launcher/examples/test/test' {
  declare module.exports: any;
}

declare module 'karma-sauce-launcher/gruntfile' {
  declare module.exports: any;
}

declare module 'karma-sauce-launcher/lib/sauce_connect' {
  declare module.exports: any;
}

declare module 'karma-sauce-launcher/lib/sauce_launcher' {
  declare module.exports: any;
}

declare module 'karma-sauce-launcher/lib/sauce_reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-sauce-launcher/examples/karma.conf-ci.js' {
  declare module.exports: $Exports<'karma-sauce-launcher/examples/karma.conf-ci'>;
}
declare module 'karma-sauce-launcher/examples/src/main.js' {
  declare module.exports: $Exports<'karma-sauce-launcher/examples/src/main'>;
}
declare module 'karma-sauce-launcher/examples/test/test.js' {
  declare module.exports: $Exports<'karma-sauce-launcher/examples/test/test'>;
}
declare module 'karma-sauce-launcher/gruntfile.js' {
  declare module.exports: $Exports<'karma-sauce-launcher/gruntfile'>;
}
declare module 'karma-sauce-launcher/index' {
  declare module.exports: $Exports<'karma-sauce-launcher'>;
}
declare module 'karma-sauce-launcher/index.js' {
  declare module.exports: $Exports<'karma-sauce-launcher'>;
}
declare module 'karma-sauce-launcher/lib/sauce_connect.js' {
  declare module.exports: $Exports<'karma-sauce-launcher/lib/sauce_connect'>;
}
declare module 'karma-sauce-launcher/lib/sauce_launcher.js' {
  declare module.exports: $Exports<'karma-sauce-launcher/lib/sauce_launcher'>;
}
declare module 'karma-sauce-launcher/lib/sauce_reporter.js' {
  declare module.exports: $Exports<'karma-sauce-launcher/lib/sauce_reporter'>;
}
